### ISSUE TITLE
Brightcove module build for 64 bit

### ISSUE THREAD

**Issue by mmayantz2** [TiForward/discuss#10]
Greetings,

I have a module built in Xcode which I have converted to 64 bit, and am pointing to the new Titanium SDK in titanium.xconfig.

I can confirm that all of the settings on the module look correct, however for some reason, the build is unable to complete due to error messages indicating missing Titanium files, such as TiModule.h or TiBase.h.

I have added library files and header files from Titanium directly in the project and yet it still fails to find files, perhaps I could zip the module for analysis, but what am I doing wrong here? All of the documentation suggests that I just need to modify titanium.xconfig, however I can confirm that is not the problem.

**Comment by mattapperson** [comment]
This error is the result of the Ti build scripts for modules looking for the Ti SDK in a place where it is not on your computer, or looking for a Ti version that you do not have installed. Please refer to the Appcelerator module docs for how to ensure the module config is set correctly for your system.

Thanks,
Matt

**Comment by Sophrinix** [comment]
There are a few things to try.
Do all of this stuff first. https://wiki.appcelerator.org/display/guides2/iOS+Module+64-bit+Support

If you are still having issues after doing everything in that wiki article then I am more than happy to skype or call you. I've been though this process with several modules already.

**Comment by mmayantz2** [comment]
Okay guys, well thank you for the prompt replies, but to be honest I have just begun using XCode and am taking up the code of a colleague and after attempting the strategies highlighted in the link above I am still running into the same issue, further the only titanium sdk being referenced that I can locate in the project is 3.5.1 which is the latest version that I just installed.

I changed the target architectures to $(ARCHS_STANDARD) and initially this architecture was not found until I added it into the manifest, now this architecture reads correctly, but still TiVewProxy.h and TiModule.h cannot be found.

Color me frustrated...perhaps I could zip the module and attach it? This may provide some insight...?

**Comment by mattapperson** [comment]
@mmayantz2 in the titanium.xcconfig the TITANIUM_SDK property, is it set correctly? User vs system Library directory is a very common cause of this issue.

Your issue is related to the setup of your exact system. So uploading the module to someone would do little to help.

**Comment by mmayantz2** [comment]
This is the set up for titanium.xconfig, I've checked it many times, it looks good, where else would there be a reference to the titanium sdk? :)

EDIT: $HOME echo's out to the correct path, it looks good.

TITANIUM_SDK_VERSION = 3.5.1.GA

//
// THESE SHOULD BE OK GENERALLY AS-IS
//
PODS_ROOT = /Volumes/Data/apps/brightcove_ios_2014/Pods
TITANIUM_SDK = "$(HOME)/Library/Application Support/Titanium/mobilesdk/osx/$(TITANIUM_SDK_VERSION)"
TITANIUM_BASE_SDK = "$(TITANIUM_SDK)/iphone/include"
TITANIUM_BASE_SDK2 = "$(TITANIUM_SDK)/iphone/include/TiCore"
HEADER_SEARCH_PATHS= $(TITANIUM_BASE_SDK) $(TITANIUM_BASE_SDK2)

**Comment by mattapperson** [comment]
@mmayantz2 so you are able to run:
`cd "~/Library/Application Support/Titanium/mobilesdk/osx/3.5.1.GA"`
and that directory exists?

**Comment by mmayantz2** [comment]
Well no it doesnt, but the path provided above reads:

Users/<username/Library/Application Support/  etc...

Why the tilde? :)

**Comment by mattapperson** [comment]
The '~' in unix / Linux / Mac is a shortcut to `/Users/<username>` 
If the command I gave you does not work, there is something incorrect about your path

**Comment by mmayantz2** [comment]
This works: 

cd ~/Library/Application\ Support/Titanium/mobilesdk/osx/3.5.1.GA (without the quotes... :P)

I see no other ref to Titanium mobile sdk elsewhere in the module, I suppose theres something else amiss.

**Comment by mattapperson** [comment]
@mmayantz2 if you are cool with sharing your terminal with me via one of the various methods I would be happy to hop on and take a look. 

This issue is a common one but have never seen it be the result of anything except a pathing issue

**Comment by mmayantz2** [comment]
That would be great! Is there an online tool I could use for such a purpose?

**Comment by mattapperson** [comment]
A number of them. Just google terminal sharing

**Comment by mmayantz2** [comment]
installing homebrew and tmate right now

**Comment by mmayantz2** [comment]
Ok its installed and running, what do you need to join ssh session, my IP address?

**Comment by mattapperson** [comment]
run the tmate command, then email me the URL matt@appersonlabs.com

**Comment by mattapperson** [comment]
Module config was all kinds of screwed up... pointed him to http://gitt.io/component/com.appersonlabs.brightcove

**Comment by mmayantz2** [comment]
Why does the documentation on your module is so badly written? :) There isn't a
workable example or specifics of how to feed the video file to a player,
unless we just pass it as a url?

Thanks

**Comment by mattapperson** [comment]
@mmayantz2 you mean like the full docs supplied here in the module when you click to view docs?

**Comment by yuchi** [comment]
(Sorry @mmayantz2 I redacted your comment for politeness! Didn’t change the meaning anyway :P )

**Comment by mmayantz2** [comment]
So I had no idea this was posting on this thread, I thought it was via email only....my bad lol
