### ISSUE TITLE
Async approach (developer experience)

### ISSUE THREAD

**Issue by yuchi** [TiForward/discuss#3]
There’s a lot of movement about this.
- https://github.com/iojs/NG/issues/1 about ES7 async/await-oriented APIs
- https://github.com/iojs/io.js/issues/11 using Promises for async APIs
- ~~https://github.com/petkaantonov/bluebird/issues/415 about Promises not being a good shape for IO~~
- https://github.com/whatwg/fetch/issues/27 about `fecth()` not being _easily_ cancellable

**Comment by omorandi** [comment]
An async API à la node is surely desirable, especially for i/o intensive operations, though I'd be happy to see it callback-based. Promises can be used on top of that

**Comment by yuchi** [comment]
For sure we have to _embrace the async_. IMHO the APIs should be async-first.

**Comment by petkaantonov** [comment]
> petkaantonov/bluebird#415 about Promises not being a good shape for IO

That issue is not about promises not being in good shape for I/O at all, there is literally nothing in that issue about that!

**Comment by yuchi** [comment]
Sorry looks like I eventually copypasted something wrong.

**Comment by petkaantonov** [comment]
It probably originated from this tweet https://twitter.com/mattpodwysocki/status/583332498844696576 the issue is linked with same reasoning there as well. I tried to ask him why he would link it and got no answer.

**Comment by yuchi** [comment]
@petkaantonov You’re totally right, and it got caught in my short list of references.

**Comment by yuchi** [comment]
Closing for obsolescence
