### ISSUE TITLE
Layout engine

### ISSUE THREAD

**Issue by yuchi** [TiForward/discuss#6]
We have a lot of different opportunities here, and a lot of competing standards to choose from.

This discussion is not about how the developer experience of writing the view hierarchy (that is what happens in Alloy XML views) but about how we define the layout itself (that is the Ti.Current `layout` property semantics).
- CSS’ Box Model
- CSS’ (and React’s) Flex Box model
- Cocoa Autolayout (Apple)
- [Android’s LayoutParams](https://developer.android.com/reference/android/view/ViewGroup.LayoutParams.html)
- [Current Titanium’s](http://docs.appcelerator.com/titanium/latest/#!/guide/Transitioning_to_the_New_UI_Layout_System)
- [Grid Style Sheets](http://gridstylesheets.org/)

IMHO Flexbox is very powerful, but not enough for real world apps. A mix of it and a constraints solving algorithm (GSS and Autolayout) would be awesome.

**Comment by mattapperson** [comment]
Obviously we need to support Ti.Current's layout for legacy support. If that is the only layout option is what this discussion should be about. Or perhaps if the layout engine should be pluggable.

**Comment by omorandi** [comment]
Native views will obviously use the native layout system. The framework shouldn't enforce anything at this level. 
What you build on top can expose a different mechanism, but it makes sense thinking that Ti.Next layout system should support Ti.Current's one, as per @mattapperson comment.

**Comment by yuchi** [comment]
> @mattapperson said: Obviously we need to support Ti.Current's layout for legacy support

May I rephrase that as «If we want to achieve legacy support the Ti.Current layout engine must be implemented»?

> @omorandi said: Native views will obviously use the native layout system

While this is true we currently have no access to the underlying layout system, so this discussion should answer the following questions:
- will we be able to access the underlying platform layout system? If yes, how?
- will we polyfill a different layout system as we currently do in Ti.Current? if yes, where will that happen? In the core or as a different layer?
- if we polyfill the layout system and _bring balance in the platforms_, which side will we take? Ti.Current? CSS Box model? Constraints solving one?

**Comment by omorandi** [comment]
@yuchi my comment assumes we're talking about a system (like hyperloop) where the developer is able to directly instantiate native objects in JS. At the very minimum, on iOS you'd be able to set the view autoresizing mask, manipulate the view frame manually or using autolayout, while on Android you'd have to play with LayoutParams (this should answer you first bulltet point). IMO the Ti.Next API should sit on top of this (i.e. the native layout system) and it can provide its higher level layout system, which could be Ti.Current's one, or whatever else.

**Comment by jonatansberg** [comment]
> GSS is a CSS preprocessor & JS runtime that harnesses Cassowary.js, the JS port of the same constraint solving algorithm Apple uses in Cocoa Autolayout for iOS & OS X.

From the "Polyfills from a Better Future" section on http://gridstylesheets.org. 

If GSS is as pwerful and useful as they claim, then it's definitely an option worth exploring. It's made by the same guys that are building [The Grid](http://thegrid.io), and they seem to have a fairly good idea of what they're doing.

**Comment by iotashan** [comment]
> @yuchi : May I rephrase that as «If we want to achieve legacy support the Ti.Current layout engine must be implemented»?

No, I think @mattapperson had it right the first time... If there's no legacy support, game over man!

**Comment by mattapperson** [comment]
Correct. We can and should support a more modern layout API, but we absolutely MUST support the current method too. Even Apple knows this and does not just support auto layout.

**Comment by mattapperson** [comment]
Sorry for closing, accidentally tapped close when on my phone 😕

**Comment by TheBrousse** [comment]
I don't know who came up with the term plugable earlier but I think it would be the way to go. 

Legacy mode would get the current ti layout. This making sure Alloy apps still work.

But I would recommend that the native tooling layout managers be used for each platform. Let's face it, android apps are not just ripoffs of the ios UI anymore. (Material, win phone, etc) And trying to come up with a common denominator is crazy. (Apps are not websites)

This would allow developers to leverage the actual native tools that are already out there in terms of UI creation. (Storyboard for ios and xml layouts and themes for Android)

**Comment by hanih** [comment]
What I would love to see in the new implementation is support for native right-to-left UI like http://developer.android.com/about/versions/android-4.2.html#RTL

**Comment by iotashan** [comment]
If layout isn't common (abstracted) across platforms, then we're back to React Native... write multiple, similar apps with a common language. I might as well just use that, or go fully-native. Yes, that means some compromises, but I think they are worth it. If you happen to need a special, platform-specific layout whatever, then a module or JS access to the native APIs are better suited for that purpose.

**Comment by mattapperson** [comment]
Also, there is nothing saying native storyboards/xml layout can not coexist with a common layout Api

**Comment by TheBrousse** [comment]
Hence my "pluggable" reference in the first place. But for discussion's sake. why would there be a need to create  common layout engine if there is already legacy support?
Date: Tue, 7 Apr 2015 07:18:08 -0700

**Comment by mattapperson** [comment]
Legacy support is ok, but in my mind a cross platform "auto layout" is needed for complex cross platform layout. But yes if it's pluggable then it becomes a non issue and the best layout systems will just become popular

**Comment by yuchi** [comment]
A pluggable layout engine is not a piece of cake. It would IMHO add a lot of unnecessary complexity.

As Jason would say, we need to adapt, and the issue currently is that we cannot break the walled garden and adapt to the underlying platform system. This is not limited to the topic at hand.

The layout system is probably one of those spots where the discussion gets tricky.

If we could make the next UI infrastructure opt-in then we'd have a ‘pluggable’ system, and eventually new layout engines could be born in user land.

**Comment by hanih** [comment]
How hard is it to come up with somthing that does not break legacy code while addressing the shortcomings of the old system ? For example I am unhappy with the scrollable view flickering each time i add an image on android

**Comment by mattapperson** [comment]
@hanih without looking into it, I would venture to guess that this is related more to bridge speed then anything else. If not that, then my assumption would be you need some sort of auto layout to manage things because too much of the visible layers are being updated for the system to work smoothly. Without digging in more though I cant say for sure

**Comment by TheBrousse** [comment]
The main goal behind what I have in mind is because right now, Ti developers have to code their UI by code. Which may be fine for us who are more experiences with the framework. But in the big picture, the tooling is very important to some developers.

So my argument is this; why going through the trouble on developing our own NEW thing (not talking about legacy here) when we can "piggy back" on the existing toolset Apple, Google and MSFT in spending millions on already?

**Comment by mattapperson** [comment]
For reference, sake. This project exists -> https://github.com/yomybaby/VirtualTiExample
A "virtual dom" for Ti native UI

**Comment by yomybaby** [comment]
Virtual dom is not related to layout system. It's a creating and updating view method. See [readme.md of virtual-dom repo](https://github.com/Matt-Esch/virtual-dom/blob/master/README.md).  

> virtual-dom is a collection of modules designed to provide a declarative way of representing the DOM for your app. So instead of updating the DOM when your application state changes, you simply create a virtual tree or VTree, which looks like the DOM state that you want. virtual-dom will then figure out how to make the DOM look like this efficiently without recreating all of the DOM nodes.
> virtual-dom allows you to update a view whenever state changes by creating a full VTree of the view and then patching the DOM efficiently to look exactly as you described it. This results in keeping manual DOM manipulation and previous state tracking out of your application code, promoting clean and maintainable rendering logic for web applications.

So I'll create another issue for concept of virtual-dom and share experimental results within a few days.

**Comment by mattapperson** [comment]
@yomybaby Yea I was just too lazy to create a new issue and this was the closest one :)

**Comment by yuchi** [comment]
@yomybaby keep me in the morning loop cause I'm digging into ES6 and JSX transformations, please.

**Comment by yuchi** [comment]
Closing for obsolescence
